<template>
  <div class="h-screen flex flex-col justify-start Lottery bg-gray-800">
    <div class="m-auto">
      <div class="Profile relative">
        <img v-for="(candidate) in stillCandidates" :key="candidate.id" class="ProfilePic object-contain absolute m-auto top-0 right-0 left-0 rounded-lg" :src="candidate.profileSrc">
        <img v-if="animatedCandidate" :key="animatedCandidate.id" :style="{ 'animation-duration': transitionSpeed }" class="ProfilePic m-auto top-0 right-0 left-0 swing-in-bottom-bck object-contain absolute rounded-lg" :src="animatedCandidate.profileSrc">
      </div>
      <div class="h-32 bg-gray-800 mt-4 m-12 rounded-lg p-4 fade-in-text text-gray-100" v-visible="rotationDone">
        <h3 class="border-dashed select-none leading-relaxed border-b-4 border-gray-100 text-6xl text-center" @click="reveal" >
          <span class="fade-in-text" v-if="revealed">
            {{nextCandidate.name}}
          </span>
          <span v-else >
            ?
          </span>
        </h3>
      </div>
       <button v-if="revealed" class="absolute bottom-0 right-0 mt-4 bg-green-100 disabled:bg-gray-900 disabled:cursor-not-allowed hover:bg-green-900 rounded py-2 px-4 text-lg" @click="$router.push({name: 'calendar'})">Richtig!</button>
       <button v-if="revealed" class="absolute bottom-0 right-0 mr-32 mt-4 bg-red-100 disabled:bg-gray-900 disabled:cursor-not-allowed hover:bg-red-900 rounded py-2 px-4 text-lg" @click="$router.push({name: 'zonk'})">Leider falsch</button>
    </div>
  </div>
</template>

<script lang="ts">
import Component from 'vue-class-component'
import Vue from 'vue'
import { useStore } from 'vuex-simple'
import { WeddingQuiz, Candidate } from '@/store'
import { Prop } from 'vue-property-decorator'
import { Dictionary } from 'vue-router/types/router'

function shuffle<T> (array: T[]) {
  var currentIndex = array.length
  var temporaryValue
  var randomIndex

  // While there remain elements to shuffle...
  while (currentIndex !== 0) {
    // Pick a remaining element...
    randomIndex = Math.floor(Math.random() * currentIndex)
    currentIndex -= 1

    // And swap it with the current element.
    temporaryValue = array[currentIndex]
    array[currentIndex] = array[randomIndex]
    array[randomIndex] = temporaryValue
  }

  return array
}

@Component({})
export default class Lottery extends Vue {
  @Prop({}) public timeout!: number

  public store: WeddingQuiz = useStore(this.$store)

  public allCandidates: Candidate[] = []

  public visibleCandidates: Candidate[] = []

  public get stillCandidates () { return this.visibleCandidates.slice(0, Math.max(this.visibleCandidates.length - 1, 0)) }
  public get animatedCandidate () { return this.visibleCandidates[this.visibleCandidates.length - 1] }

  public get nextCandidate () { return this.store.nextCandidate }

  public nextTimeout = 10
  public get transitionSpeed () { return `${this.nextTimeout}ms` }

  public rotationDone = false
  public revealed = false

  public async mounted () {
    if (!this.store.nextCandidate) {
      await this.store.selectNextCandidate()
    }
    this.allCandidates = shuffle([...this.store.candidates])
    this.startRotation()
  }

  public startRotation () {
    setTimeout(() => {
      this.nextTimeout = this.nextTimeout * 1.4
      const nextVisibleCandidate = this.allCandidates.shift()!
      this.allCandidates.push(nextVisibleCandidate)
      if (this.visibleCandidates.length > 2) {
        this.visibleCandidates.shift()
      }
      this.visibleCandidates.push(nextVisibleCandidate)
      if (this.nextTimeout > this.timeout) {
        this.rotateCandidateIn()
      } else {
        this.startRotation()
      }
    }, this.nextTimeout)
  }

  public rotateCandidateIn () {
    if (this.nextCandidate) {
      this.visibleCandidates = []
      this.visibleCandidates.push(this.nextCandidate)
    }
    setTimeout(() => { this.rotationDone = true }, this.nextTimeout)
  }

  public reveal () {
    this.revealed = true
  }
}
</script>

<style scoped>
.Lottery {
  perspective: 1000;
}

.Profile {
  display: block;
  height: 800px;
  width: 800px;
}

.ProfilePic {
  height: 100%;
  width: auto;
}

.swing-in-bottom-bck {
  animation: swing-in-bottom-bck 3s cubic-bezier(0.165, 0.840, 0.440, 1.000) both;
}

.fade-in-text {
  animation: fade-in 1s cubic-bezier(0.165, 0.840, 0.440, 1.000) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2019-10-18 0:8:22
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation swing-in-bottom-bck
 * ----------------------------------------
 */
@keyframes swing-in-bottom-bck {
  0% {
    transform: translateZ(600px);
    opacity: 0;
  }
  100% {
    transform: translateZ(0);
    opacity: 1;
  }
}

@keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}

</style>
