<template>
  <div class="h-screen flex flex-col Zonk bg-gray-800">
    <div class="m-auto">
      <div class="Profile relative">
        <img class=".swing-in-bottom-bck Profile object-contain absolute rounded-lg" src="misc/zonk.png">
      </div>
       <button class="absolute bottom-0 right-0 mt-4 bg-green-100 disabled:bg-gray-900 disabled:cursor-not-allowed hover:bg-green-900 rounded py-2 px-4 text-lg" @click="backToCalendar">Zurück zum Kalender</button>
    </div>
  </div>
</template>

<script lang="ts">
import Component from 'vue-class-component'
import Vue from 'vue'
import { useStore } from 'vuex-simple'
import { WeddingQuiz, Candidate } from '@/store'
import { Prop } from 'vue-property-decorator'
import { Dictionary } from 'vue-router/types/router'

@Component({})
export default class Zonk extends Vue {
  public store: WeddingQuiz = useStore(this.$store)

  public async backToCalendar () {
    await this.store.clearNextCandidate()
    this.$router.push({ name: 'calendar' })
  }
}
</script>

<style scoped>
.Zonk {
  perspective: 1000;
}

.Profile {
  display: block;
  height: 1000px;
  width: 1000px;
}

.swing-in-bottom-bck {
  animation: swing-in-bottom-bck 3s cubic-bezier(0.165, 0.840, 0.440, 1.000) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2019-10-18 0:8:22
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation swing-in-bottom-bck
 * ----------------------------------------
 */
@keyframes swing-in-bottom-bck {
  0% {
    transform: translateZ(600px);
    opacity: 0;
  }
  100% {
    transform: translateZ(0);
    opacity: 1;
  }
}

</style>
